LazmekUI/Areas/Admin/Controllers/DashboardController.cs
using DataAccess.Repository;
using DataAccess.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.ViewModels;
using MyProject.Models;
using Utility;




namespace MyProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class DashboardController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        public DashboardController(IUnitOfWork unitOfWork)
        {
            _unitofwork = unitOfWork;
        }
        public IActionResult Index(int timePeriod)
        {
            if (timePeriod == 0)
            {
                timePeriod = 1;
            }
            DashboardVM dashBoardVM;
            dashBoardVM = new DashboardVM
            {
                timePeriod= timePeriod,

                numberOfUsers = _unitofwork.ApplicationUser.GetAll().Count(),

                numberOfProducts = _unitofwork.Product.GetAll().Count(),

                numberOfOrders = _unitofwork.OrderHeader.GetAll().Count(),

                financialActivities=_unitofwork.OrderHeader.GetAll(o=>o.PaymentStatus==SD.PaymentStatusApproved || o.PaymentStatus==SD.PaymentStatusRejected).Select(o=>new WalletActivities {total=o.OrderTotal,status=o.PaymentStatus }).ToList()
            };
            if (timePeriod == 1)
            {                
                dashBoardVM.growNumberOfUsers = _unitofwork.ApplicationUser.GetAll(u => u.CreateAt == DateOnly.FromDateTime(DateTime.Today)).Count();
                     
                dashBoardVM.growNumberOfProducts = _unitofwork.Product.GetAll(u => u.CreateAt == DateOnly.FromDateTime(DateTime.Today)).Count();
                     
                dashBoardVM.growNumberOfOrders = _unitofwork.OrderHeader.GetAll(u => u.OrderDate.Date == DateTime.Today.Date).Count();
                     
                dashBoardVM.totalOfSales = _unitofwork.OrderHeader.GetAll(u => u.OrderDate == DateTime.Today).Select(o => o.OrderTotal).Sum();
                dashBoardVM.growTotalOfSales = ((_unitofwork.OrderHeader.GetAll(u => u.OrderDate.AddDays(1) == DateTime.Today).Select(o => o.OrderTotal).Sum()
                - _unitofwork.OrderHeader.GetAll(u => u.OrderDate.Date == DateTime.Today).Select(o => o.OrderTotal).Sum()) / 100);               
            }
            else
            {
                dashBoardVM.growNumberOfUsers = _unitofwork.ApplicationUser.GetAll(u => u.CreateAt < DateOnly.FromDateTime(DateTime.Today) && u.CreateAt.AddDays(timePeriod) >= DateOnly.FromDateTime(DateTime.Today)).Count();

                dashBoardVM.growNumberOfProducts = _unitofwork.Product.GetAll(u => u.CreateAt < DateOnly.FromDateTime(DateTime.Today) && u.CreateAt.AddDays(timePeriod) >= DateOnly.FromDateTime(DateTime.Today)).Count();

                dashBoardVM.growNumberOfOrders = _unitofwork.OrderHeader.GetAll(u => u.OrderDate < DateTime.Today && u.OrderDate.AddDays(timePeriod) >= DateTime.Today).Count();

                dashBoardVM.totalOfSales = _unitofwork.OrderHeader.GetAll(u => u.OrderDate < DateTime.Today && u.OrderDate.AddDays(timePeriod) >= DateTime.Today).Select(o => o.OrderTotal).Sum();
                dashBoardVM.growTotalOfSales = ((_unitofwork.OrderHeader.GetAll(u => u.OrderDate < DateTime.Today && u.OrderDate.AddDays(timePeriod) >= DateTime.Today).Select(o => o.OrderTotal).Sum()
                - _unitofwork.OrderHeader.GetAll(u => u.OrderDate < DateTime.Today.AddDays(-timePeriod) && u.OrderDate.AddDays(timePeriod) >= DateTime.Today.AddDays(-timePeriod)).Select(o => o.OrderTotal).Sum()) / 100);
            }
            return View(dashBoardVM);
        }
        

    }//end controller
}

LazmekUI/Areas/Customer/Controllers/CartController.cs
using DataAccess.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models;
using Models.ViewModels;
using Stripe.Checkout;
using System.Security.Claims;
using Utility;

namespace MyProject.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            
            ShoppingCartVM =new() { 
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u=>u.UserID==userId,includeProperties: "product").ToList(),
                orderHeader=new OrderHeader()
            };

            IEnumerable<ProductImage> productImages = _unitOfWork.ProductImage.GetAll().ToList();
            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {
                cart.product.ProductImages = productImages.Where(p=>p.ProductId==cart.product.Id).ToList();
                cart.CartPrice = GetPriceBasedOnQuantity(cart);
                ShoppingCartVM.orderHeader.OrderTotal += (cart.Count * cart.CartPrice);
            }
            return View(ShoppingCartVM);
        }
        public IActionResult Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.UserID == userId, includeProperties: "product"),
                orderHeader = new OrderHeader()
            };

            ShoppingCartVM.orderHeader.user = _unitOfWork.ApplicationUser.Get(u => u.Id == userId);
            ShoppingCartVM.orderHeader.Name = ShoppingCartVM.orderHeader.user.Name;
            ShoppingCartVM.orderHeader.StreetAddress = ShoppingCartVM.orderHeader.user.StreetAddress;
            ShoppingCartVM.orderHeader.PhoneNumber = ShoppingCartVM.orderHeader.user.PhoneNumber;
            ShoppingCartVM.orderHeader.Country = ShoppingCartVM.orderHeader.user.Country;
            ShoppingCartVM.orderHeader.City = ShoppingCartVM.orderHeader.user.City;
            ShoppingCartVM.orderHeader.PostalCode = ShoppingCartVM.orderHeader.user.PostalCode;

            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {
                cart.CartPrice = GetPriceBasedOnQuantity(cart);
                ShoppingCartVM.orderHeader.OrderTotal += (cart.Count * cart.CartPrice);
            }
            return View(ShoppingCartVM);
        }
        [HttpPost]
        [ActionName("Summary")]
        public IActionResult SummaryPOST()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM.ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.UserID == userId, includeProperties: "product");
            
            ShoppingCartVM.orderHeader.UserID = userId;
            ShoppingCartVM.orderHeader.OrderDate = DateTime.Now;

            ApplicationUser AppUser = _unitOfWork.ApplicationUser.Get(u=>u.Id==userId);
            
            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {
                cart.CartPrice = GetPriceBasedOnQuantity(cart);
                ShoppingCartVM.orderHeader.OrderTotal += (cart.Count * cart.CartPrice);
            }

            ShoppingCartVM.orderHeader.OrderStatus=SD.StatusPending;
            ShoppingCartVM.orderHeader.PaymentStatus=SD.PaymentStatusPending;            
            _unitOfWork.OrderHeader.Add(ShoppingCartVM.orderHeader);
            _unitOfWork.Save();

            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {
                OrderDetail orderDetail = new()
                {
                    ProductId = cart.ProductId,
                    OrderHeaderId=ShoppingCartVM.orderHeader.Id,
                    Count=cart.Count,
                    Price=cart.CartPrice,
                };
                _unitOfWork.OrderDetail.Add(orderDetail);
            }
            _unitOfWork.Save();

            //payment Logic
            var Domin = "https://localhost:7224";
            var options = new Stripe.Checkout.SessionCreateOptions
            {
                SuccessUrl =Domin+ $"/customer/cart/orderconfirmation?id={ShoppingCartVM.orderHeader.Id}",
                CancelUrl=Domin+$"/customer/cart/Index",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
            };
            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {
                var sessionLineItem = new SessionLineItemOptions()
                {
                    PriceData= new SessionLineItemPriceDataOptions()
                    {
                        UnitAmount= (long)cart.CartPrice*100,    // convert 20.75$ => 2075
                        Currency="usd",
                        ProductData=new SessionLineItemPriceDataProductDataOptions()
                        {
                            Name=cart.product.Title
                        }
                    },
                    Quantity=cart.Count
                };
                options.LineItems.Add(sessionLineItem);
            }
            var service = new SessionService();
            Session session = service.Create(options);
            _unitOfWork.OrderHeader.UpdateStripePaymentId(ShoppingCartVM.orderHeader.Id,session.Id,session.PaymentIntentId);            
            _unitOfWork.Save();
            Response.Headers.Add("Location",session.Url);
            return new StatusCodeResult(303);           
        }
        public IActionResult OrderConfirmation(int orderHeaderId)
        {
            var orderHeadeFromDb = _unitOfWork.OrderHeader.Get(x => x.Id == orderHeaderId);
            
            var service = new SessionService();
            Session session = service.Get(orderHeadeFromDb.SessionId);
            if (session.PaymentStatus.ToLower()=="paid" )
            {
                _unitOfWork.OrderHeader.UpdateStripePaymentId(orderHeaderId,session.Id,session.PaymentIntentId);
                _unitOfWork.OrderHeader.UpdateStatus(orderHeaderId,SD.StatusApproved,SD.PaymentStatusApproved);
                _unitOfWork.Save();
            }
            
            var cartsFromDb= _unitOfWork.ShoppingCart.GetAll(x=>x.UserID==orderHeadeFromDb.UserID).ToList();
            foreach(var cart in cartsFromDb)
            {
                var productFromDb = _unitOfWork.Product.Get(p=>p.Id==cart.ProductId,traked:true);
                if (productFromDb.Quantity - cart.Count >= 0)
                {
                    productFromDb.Quantity -= cart.Count;
                }
                _unitOfWork.Save();                 
            }
            _unitOfWork.ShoppingCart.RemoveRange(cartsFromDb);
            _unitOfWork.Save();
            HttpContext.Session.Clear();            
            return View(orderHeaderId);
        }
        public IActionResult plus(int Id)
        {
            var cartFromDb =_unitOfWork.ShoppingCart.Get(c=>c.Id==Id);
            cartFromDb.Count += 1;
            _unitOfWork.ShoppingCart.Update(cartFromDb);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
        public IActionResult minus(int Id)
        {
            var cartFromDb =_unitOfWork.ShoppingCart.Get(c=>c.Id==Id,traked: true);
            if (cartFromDb.Count > 1)
            {
                cartFromDb.Count -= 1;
                _unitOfWork.ShoppingCart.Update(cartFromDb);
            }
            else
            {
                _unitOfWork.ShoppingCart.Remove(cartFromDb);
                var countCart = _unitOfWork.ShoppingCart.GetAll(u => u.UserID == cartFromDb.UserID).Count() - 1;
                HttpContext.Session.SetInt32(SD.SessionShoppingCart, countCart);
            }
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
        public IActionResult remove(int Id)
        {
            var cartFromDb =_unitOfWork.ShoppingCart.Get(c=>c.Id==Id,traked:true);
            _unitOfWork.ShoppingCart.Remove(cartFromDb);
            var countCart = _unitOfWork.ShoppingCart.GetAll(u => u.UserID == cartFromDb.UserID).Count()-1;
            HttpContext.Session.SetInt32(SD.SessionShoppingCart, countCart);    
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }
        private double GetPriceBasedOnQuantity(ShoppingCart Cart)
        {
            if (Cart.Count<=50)
            {
                return Cart.product.Price;
            }else if (Cart.Count <= 100)
            {
                return Cart.product.Price50;
            }
            else
            {
                return Cart.product.Price100;
            }
        }
    }
}

LazmekUI/Areas/Customer/Controllers/OrderHeaderController.cs
using DataAccess.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;
using Models.ViewModels;
using MyProject.Models;
using Stripe;
using Stripe.Checkout;
using Stripe.Climate;
using System.Diagnostics;
using System.Security.Claims;
using Utility;

namespace LazmekUI.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class OrderHeaderController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        [BindProperty]
        private OrderVM orderVM { get; set; }
        public OrderHeaderController(IUnitOfWork unitOfWork)
        {
            _unitofwork = unitOfWork;

        }
        public IActionResult Index()
        {
            var claim = (ClaimsIdentity)User.Identity;
            var userId = claim.FindFirst(ClaimTypes.NameIdentifier).Value;
            var listOrder = _unitofwork.OrderHeader.GetAll(o=>o.UserID==userId,includeProperties:"user").ToList();
            return View(listOrder);
        }
        public IActionResult Details(int orderId)
        {
            orderVM = new OrderVM
            {
                orderHeader = _unitofwork.OrderHeader.Get(x => x.Id == orderId, includeProperties: "user"),
                orderDetail = _unitofwork.OrderDetail.GetAll(x => x.OrderHeaderId == orderId, includeProperties: "product").ToList()
            };            
            return View(orderVM);
        }

    }//end controller
}

LazmekUI/ViewComponents/ShoppingCartViewComponent.cs
using DataAccess.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Utility;

namespace MyProject.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent( IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {                
                if (HttpContext.Session.GetInt32(SD.SessionShoppingCart) == null)
                {
                    var cartCount = _unitOfWork.ShoppingCart.GetAll(u => u.UserID == claim.Value).Count();
                    HttpContext.Session.SetInt32(SD.SessionShoppingCart, cartCount);
                }
                return View(HttpContext.Session.GetInt32(SD.SessionShoppingCart));                 
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }            
        }

    }
}

LazmekUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Lazmek</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/MyProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm px-5 navbar-toggleable-sm navbar-light bg-gold text-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand font-monospace" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    
                    <img src="/images/Lazmek_Logo.png" style="width:155px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex align-items-center ">
                    <ul class="navbar-nav flex-grow-1 me-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="OrderHeader" asp-action="Index">My Orders</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">@await Component.InvokeAsync("ShoppingCart")  </a>
                        </li> 
                        <li class="nav-item">
                        </li>                 
                    </ul>
                    <div class="my-sm-3 my-md-0 w-50 me-2 position-relative align-items-center justify-content-center">
                        <form asp-area="Customer" asp-controller="Home" asp-action="Index" method="get">
                            <button type="submit" class="search-btn">
                                <i class="fas fa-search search-icon"></i>
                            </button>
                            <input type="text" name="search" class="form-control search-input text-opacity-25" placeholder="Search...">
                        </form>
                    </div>
                    @if(User.IsInRole(SD.Role_Admin))
                    {
                        <a class="nav-item bg-black mx-3 ">
                            <a class="nav-link fw-bolder" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Dashbord</a>
                        </a>                            
                    }                        
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid overflow-x-hidden  px-0 mx-0" style="margin-top:100px">
        <main role="main">
            <partial name="_Notifications"/>
            @RenderBody()
        </main>
    </div>
    <div id ="whychoseus" class=" py-5 bg-dark-mode ">
        <div class="container pt-5">
            <h2  class="text-center mb-4 text-white">Why Choose Us?</h2>
            <div class="row text-center">

                <div class="col-md-3 mb-3">
                    <div class="card card-hover bg-dark-mode h-100 shadow-lg  border-0">
                        <div class="card-body">
                            <i class="bi bi-currency-dollar display-4 text-success"></i>
                            <h4 class="card-title text-success">Best Prices</h4>
                            <p class="card-text text-white-50">
                                We offer competitive prices without compromising on quality.
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 mb-3">
                    <div class="card card-hover bg-dark-mode h-100 shadow-lg border-0">
                        <div class="card-body ">
                            <i class="bi bi-truck display-4 text-warning"></i>
                            <h4 class="card-title text-warning">Fast Delivery</h4>
                            <p class="card-text text-white-50">
                                Get your order delivered quickly and on time.
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 mb-3">
                    <div class="card card-hover bg-dark-mode h-100 shadow-lg border-0">
                        <div class="card-body">
                            <i class="bi bi-award display-4 text-info"></i>
                            <h4 class="card-title text-info">Trusted by Customers</h4>
                            <p class="card-text text-white-50">
                                Over 10,000 satisfied customers trust our services.
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 mb-3">
                    <div class="card card-hover bg-dark-mode h-100 shadow-lg border-0">
                        <div class="card-body">
                            <i class="bi bi-headset display-4 text-light"></i>
                            <h4 class="card-title text-light"> Support 24/7</h4>
                            <p class="card-text text-white-50">
                                We’re here whenever you need us.
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="container-fluid pt-5 mt-0 border-0 border-top border-dark bg-dark-mode text-white align-items-center ">
        <div class="row text-center">
            <div class="col-md-4 col-12 mb-3">
                <h5>Lazmek</h5>
                <p class="text-white-50" >
                    Your trusted place for quality products at the best prices.
                    We offer a wide range of items with durability and style, fast delivery,
                    and reliable support for a simple shopping experience.
                </p>
            </div>
            <div class="col-md-4 col-12 mb-3">
                <h5>Quick Links</h5>
                <ul class="list-unstyled">
                    <li><a href="#" class="link link-dark  text-white-50 text-decoration-none">Back To Top</a></li>
                    <li><a href="#" class="link link-dark  text-white-50 text-decoration-none">Home</a></li>
                    <li><a href="#" class="link link-dark  text-white-50 text-decoration-none">Your Orders</a></li>
                    <li><a href="#" class="link link-dark  text-white-50 text-decoration-none">Shopping</a></li>
                </ul>
            </div>
            <div class="col-md-4 col-12 mb-3">
                <h5>Contact Us</h5>
                <p class="text-white-50">Email: Lazmek@gmail.com</p>
                <p class="text-white-50">Phone: +962 7 9999 9999</p>
                <div>
                    <a href="#" class=" link link-dark "><i class="bi bi-whatsapp mx-1 text-white-50"></i></a>
                    <a href="#" class=" link link-dark "><i class="bi bi-facebook mx-1 text-white-50"></i></a>
                    <a href="#" class=" link link-dark "><i class="bi bi-linkedin mx-1 text-white-50"></i></a>
                    <a href="#" class=" link link-dark "><i class="bi bi-github mx-1 text-white-50"></i></a>            
                </div>
            </div>
        </div>
    </div>
    <footer class="footer text-white text-opacity-50 m-0 bg-black text-center align-content-center " style="height:50px">                
            <span>&copy; 2025 bowered by Khalid Al-Kurdi <i class="bi bi-balloon-heart"></i> </span>       
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/2smc81gpk08kfr89h5sv2yfs3wmvf5djkcqwlf9drkvbyxee/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LazmekUI/Views/Shared/_Notifications.cshtml
@if(TempData["success"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
   
}
@if (TempData["update"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["update"]');
    </script>
}@if (TempData["delete"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.warning('@TempData["delete"]');
    </script>
}