LazmekUI/Areas/Admin/Controllers/ProductController.cs
using DataAccess.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;
using Models.ViewModels;
using MyProject.Models;
using Utility;

namespace MyProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork , IWebHostEnvironment webHostEnvironment )
        {
           _unitofwork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
           
            return View();
        } 
        public IActionResult UpSert(int? id)
        {

            ProductVM productVM = new ProductVM()
            {
                CategoryList = _unitofwork.Category.GetAll().Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                product = new Product()
            };
            
            if (id == null || id == 0)
            {//create
                return View(productVM);
            }
            else
            {//update
                productVM.product = _unitofwork.Product.Get(u => u.Id == id, includeProperties:"ProductImages");
                return View(productVM);
            }
        }
        [HttpPost]
        public IActionResult UpSert(ProductVM productVM,List<IFormFile>? files)
        {
            if (ModelState.IsValid)
            {
                string wwwRoot = _webHostEnvironment.WebRootPath;
                //case -- update --    
                if (productVM.product.Id !=null && productVM.product.Id != 0)
                { 
                    _unitofwork.Product.Update(productVM.product);
                    if (productVM.product.ProductImages != null)
                    {
                        foreach (var image in productVM.product.ProductImages)
                        {
                            //delet old image
                            var oldimagepath = Path.Combine(wwwRoot, image.ImageUrl.TrimStart('\\'));
                            if (System.IO.File.Exists(oldimagepath))
                            {                           
                                System.IO.File.Delete(oldimagepath);
                            }

                        }                        
                    }
                    TempData["update"] = "Updated Successfuly. !";
                }
                else
                {// create new product
                    _unitofwork.Product.Add(productVM.product);
                    TempData["success"] = "Done Created. !";
                }
                _unitofwork.Save();
                
                if (files != null)
                {
                    //add images
                    foreach (IFormFile file in files)
                    {
                        string fileName = Guid.NewGuid().ToString()+Path.GetExtension(file.FileName);
                        string productPath = @"images\products\product-"+productVM.product.Id;
                        string finalPath = Path.Combine(wwwRoot, productPath);

                        if (!Directory.Exists(finalPath))
                        {
                            Directory.CreateDirectory(finalPath);
                        }
                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileName),FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                        var productImage = new ProductImage
                        {
                            ImageUrl = @"\" + productPath + @"\" + fileName,
                            ProductId= productVM.product.Id,
                        };

                        if (productVM.product.ProductImages==null)
                        {
                            productVM.product.ProductImages=new List<ProductImage>();
                        }
                        productVM.product.ProductImages.Add(productImage);
                    }
                    _unitofwork.Product.Update(productVM.product);
                    _unitofwork.Save();
                }                  
                return RedirectToAction("Index");
            }
            return View(productVM);
        }        
        #region Api Call 
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> list = _unitofwork.Product.GetAll(includeProperties: "Category").ToList();
            return Json(new { data = list});
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var productToBeDelete = _unitofwork.Product.Get(x => x.Id == id);
            if (productToBeDelete == null)
            {
                return Json(new {success= false, message="Error while delete a prouct !"});
            }
            var oldDirectoryPath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\products\product-"+id);
            if (Directory.Exists(oldDirectoryPath))
            {
                Directory.Delete(oldDirectoryPath,true);
            }
            _unitofwork.Product.Remove(productToBeDelete);
            _unitofwork.Save();
            return Json(new { success = true, message = "Delete Successfuly!" });
        }
        public IActionResult DeleteImage(int ImageId)
        {
            var ImageToBeDelete = _unitofwork.ProductImage.Get(x => x.Id == ImageId);
            if (ImageToBeDelete != null)
            {
                if(!string.IsNullOrEmpty(ImageToBeDelete.ImageUrl))
                {
                    var oldImage = Path.Combine(_webHostEnvironment.WebRootPath, ImageToBeDelete.ImageUrl.TrimStart('\\'));
                    if (System.IO.Path.Exists(oldImage))
                    {
                        System.IO.File.Delete(oldImage);
                    }
                    _unitofwork.ProductImage.Remove(ImageToBeDelete);
                    _unitofwork.Save();
                    TempData["delete"] = " The Image deleted Successfuly. !";
                }
            }            
            return RedirectToAction(nameof(UpSert), new { id = ImageToBeDelete.ProductId});
        }
        #endregion
    }//end controller
}

LazmekUI/Areas/Customer/Controllers/HomeController.cs
using DataAccess.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models;
using Models.ViewModels;
using MyProject.Models;
using System.Diagnostics;
using System.Security.Claims;
using Utility;
namespace MyProject.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Base(bool gust=false, bool asUser= false)
        {
            // redirect the user based on his role
            if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole(SD.Role_Admin) && !asUser)
                {
                    return RedirectToAction("Index", "Dashboard", new {Area="Admin"});
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }                        
            return RedirectToAction(nameof(Welcome));                                           
        }
        public IActionResult Welcome(bool gust=false)
        {
            if(gust)
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public IActionResult Index(string? search,string? category)
        {
            HomeIndexVM homeIndexVM = new HomeIndexVM
            {
                categories=_unitOfWork.Category.GetAll().OrderBy(c=>c.Name).Select(c => c.Name).ToList(),
            };     
            
            if (!string.IsNullOrEmpty(category))
            {
                homeIndexVM.categorytSelected = category;
                homeIndexVM.products = _unitOfWork.Product.GetAll(p=>p.Category.Name==category, includeProperties: "Category,ProductImages,Reviews").ToList();              
                return View(homeIndexVM);
            }
            if (!string.IsNullOrEmpty(search))
            {
                homeIndexVM.products = _unitOfWork.Product.GetAll(p=>EF.Functions.Contains( p.Title,search)|| EF.Functions.Contains(p.Description, search), includeProperties: "Category,ProductImages,Reviews").ToList();
                if (homeIndexVM.products.Any())
                {
                    homeIndexVM.NotFoundSearch = false;                
                    return View(homeIndexVM);
                }
                TempData["delete"] = "Not Found Any Matche";
            }
            homeIndexVM.products = _unitOfWork.Product.GetAll(includeProperties: "Category,ProductImages,Reviews").ToList();
            homeIndexVM.TopProducts = _unitOfWork.Product.GetAll( includeProperties: "Category,ProductImages,Reviews").Where(p=>p.Rating>4).ToList();
            return View(homeIndexVM);
        }
        [HttpGet]
        public IActionResult Details(int producdId)
        {
            var ShoppingCart = new ShoppingCart
            {
                product=_unitOfWork.Product.Get(p=>p.Id==producdId, includeProperties: "Category,ProductImages,Reviews"),
                ProductId=producdId

            };
            return View(ShoppingCart);
        }
        [Authorize]
        [HttpPost]
        [ActionName(nameof(Details))]
        public IActionResult DetailsPost(ShoppingCart cart)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            cart.UserID= userId;

            var cartFromDb = _unitOfWork.ShoppingCart.Get(sh=>sh.ProductId==cart.ProductId && sh.UserID==userId);
            if (cartFromDb != null)
            {
                cartFromDb.Count += cart.Count;
                _unitOfWork.ShoppingCart.Update(cartFromDb);
                _unitOfWork.Save();
            }
            else
            {
                _unitOfWork.ShoppingCart.Add(cart);
                _unitOfWork.Save();
                var cartCount = _unitOfWork.ShoppingCart.GetAll(u => u.UserID == userId).Count();
                HttpContext.Session.SetInt32(SD.SessionShoppingCart, cartCount);
            }

            TempData["update"] = "Cart updated successfuly!";
            return RedirectToAction("Index");
        }
        
    }
}

LazmekUI/Areas/Customer/Views/Home/Details.cshtml
@model ShoppingCart
<div class="px-5">
    <form method="post" asp-action="Details" asp-controller="Home">
        <input asp-for="@Model.ProductId" hidden />
        <div class="card shadow border-0 mt-4">
            <div class="card-header bg-dark-mode bg-gradient text-light py-4">
                <div class="row">
                    <div class="col-12 text-center">
                        <h3 class="text-white text-uppercase">@Model.product.Title</h3>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="py-3">
                    <div class="row">
                        <div class="col-6 col-md-2 offset-lg-1 pb-1">
                            <a asp-action="Index" class="btn btn-outline-dark bg-gradient mb-5 fw-semibold btn-sm text-uppercase">
                                <small>Back to home</small>
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-lg-3 offset-lg-1 text-center mb-3">

                                                                <!-- Slides -->
                            @if (Model.product.ProductImages != null && Model.product.ProductImages.Any())
                            {
                                <div id="carouselExampleIndicators" class="carousel  slide" data-bs-ride="carousel">
                                    <div class="carousel-indicators">

                                        @foreach (var imageWithIndex in Model.product.ProductImages
                                       .Select((image, index) => new { Image = image, Index = index }))
                                        {
                                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="@imageWithIndex.Index" 
                                            class="@(imageWithIndex.Index==0?"active":"")" aria-current="true" aria-label="Slide 1"></button>
                                        }


                                    </div>
                                    <div class="carousel-inner">
                                        @foreach (var imageWithIndex in Model.product.ProductImages
                                       .Select((image, index) => new { Image = image, Index = index }))
                                        {
                                            <div class="@(imageWithIndex.Index==0?"carousel-item active":"carousel-item")">
                                                <img src="@imageWithIndex.Image.ImageUrl" class="d-block w-100" alt="...">
                                            </div>
                                        }
                                    </div>
                                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="visually-hidden">Previous</span>
                                    </button>
                                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="visually-hidden">Next</span>
                                    </button>
                                </div>

                            }



                        </div>
                        <div class="col-12 col-lg-6 offset-lg-1">
                            <div class="col-12 d-flex justify-content-between  pb-4">
                                <span class="badge small ">@Model.product.Category.Name</span>

                                <span class="" data-bs-toggle="modal" data-bs-target="#ratingModal" style="cursor:pointer;">
                                    @for (int i = 1; i <= 5; i++)
                                    {
                                        if (i <= Model.product.Rating)
                                        {
                                            <i class="fa-solid fa-star text-warning"></i>
                                        }                                    
                                        else
                                        {
                                            <i class="fa-regular fa-star text-warning"></i>
                                        }
                                    }
                                    <span>/ @Model.product.Rating.ToString("0.0")</span>
                                </span>





                            </div>
                            <div class="row ps-2">
                                <h6 class="text-dark text-opacity-50 ">Brand ~ @Model.product.Brand</h6>
                            </div>
                            <div class="row ps-2">
                                <h6 class="text-dark text-opacity-50  pb-2">
                                    List Price:
                                    <span class="text-decoration-line-through">
                                        @Model.product.ListPrice.ToString("c")
                                    </span>
                                </h6>
                            </div>
                            <div class="row text-center ps-2">
                                <div class="p-1 col-3 col-lg-2 bg-white border-bottom">
                                    <div class="text-dark text-opacity-50 fw-semibold">Quantity</div>
                                </div>
                                <div class="p-1 col-3 col-lg-2 bg-white border-bottom">
                                    <div class="text-dark text-opacity-50 fw-semibold">1-50</div>
                                </div>
                                <div class="p-1 col-3 col-lg-2 bg-white border-bottom">
                                    <div class="text-dark text-opacity-50 fw-semibold">51-100</div>
                                </div>
                                <div class="p-1 col-3 col-lg-2 bg-white border-bottom">
                                    <div class="text-dark text-opacity-50 fw-semibold">100+</div>
                                </div>
                            </div>
                            <div class="row text-center ps-2">
                                <div class="p-1 col-3 col-lg-2 bg-white text-warning fw-bold">
                                    <div>Price</div>
                                </div>
                                <div class="p-1 col-3 col-lg-2 bg-white text-warning fw-bold">
                                    <div>@Model.product.Price.ToString("c")</div>
                                </div>
                                <div class="p-1 col-3 col-lg-2 bg-white text-warning fw-bold">
                                    <div>@Model.product.Price50.ToString("c")</div>
                                </div>
                                <div class="p-1 col-3 col-lg-2 bg-white text-warning fw-bold">
                                    <div>@Model.product.Price100.ToString("c")</div>
                                </div>
                            </div>
                            <div class="row pl-2 my-3">
                                <p class="text-secondary lh-sm">@Html.Raw(Model.product.Description)</p>
                            </div>
                            <div class="row pl-2 mb-3">
                                <div class="col-md-4">
                                    <div class="input-group mb-3">
                                        <span class="input-group-text bg-dark text-white border-0 fw-semibold"
                                              id="inputGroup-sizing-default">
                                            Count
                                        </span>
                                        <input asp-for="@Model.Count" type="number" value="1" class="form-control text-end"
                                               aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" />

                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-md-6 pb-1">
                                    <button type="submit"
                                            class="btn bg-gold text-dark bg-gradient  w-100 py-2 text-uppercase fw-semibold">
                                        Add to Cart
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>



    <div class="modal fade" id="ratingModal" tabindex="-1" aria-labelledby="ratingModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form asp-area="Customer" asp-controller="Product" asp-action="Rate" method="post">
                    <div class="modal-header">
                        <h5 class="modal-title" id="ratingModalLabel">Rate this product</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-center">
                        <input type="hidden" name="productId" value="@Model.product.Id" />

                        <div class="star-rating">
                            @for (int i = 5; i >= 1; i--)
                            {
                            
                                <input type="radio" name="rating" id="star-@i" value="@i" />
                                <label for="star-@i"><i class="fa-solid fa-star"></i></label>

                            }
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn text-dark bg-gold">Submit Rating</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

LazmekUI/Areas/Customer/Views/Home/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<div class="pt-2  m-0 px-0">
    <div class="row h-100 align-items-center mb-5 p-5">
        <div class="col-12 col-md-6 text-center row justify-content-center ">
            <h1 class="anmi text-primary mb-3" style="animation-delay:0.5s;">
                Welcome to
                <br />
                <span class="anmi fs-1" style="animation-delay:0.7s; letter-spacing:2rem; color:gold;">
                    Lazmek
                </span>
            </h1>
            <p class="anmi text-muted mb-4 small col-md-8 " style="animation-delay:1s;">
                Everything you need in one place.<br/>
                <span class="anmi" style="animation-delay:1.2s;">Join thousands of happy customers today!</span>
            </p>
            <div class="anmi d-flex flex-wrap justify-content-center gap-2" style="animation-delay:1.4s;">
                <a asp-area="Identity" asp-page="/Account/Login" class="btn bg-gold text-dark">Sign In</a>
                <a asp-area="Identity" asp-page="/Account/Register" class="btn btn-dark">Sign up</a>
                <a asp-area="Customer" asp-controller="Home" asp-action="Welcome" asp-route-gust="@true" class="btn btn-outline-info">Continue as Guest</a>
            </div>
            <a href="#whychoseus" class="anmi mt-3 text-muted " style="animation-delay:1.5s;"> <h5>WHY CHOOSE US ?</h5></a>
        </div>
        <div class="col-12 col-md-6 mt-3 mb-md-0 text-center">
            <img src="/images/cart.svg" class="anmi img-fluid w-75" alt="Shopping Cart" style="animation-delay:1s;" />
        </div>        
    </div>
    <div class="container-fluid bg-primary m-0 p-5 mt-5">
        <div class="row">
            <div class=" col-md-6 col-12 text-center align-content-center">
                <h2 class="text-white opacity-75">
                    Discover, What Do You Need?
                </h2>
                <h4 class="text-white-50">
                    No More Searching Everywhere - find it here...
                </h4>
            </div>
            <div class="col-md-6 col-12">
                <div id="productsCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
                    <div class="carousel-inner">                               
                        <div class="carousel-item active">
                            <img src="/images/ActiveCarsol.jpg" class="d-block w-100">
                    
                        </div>
                        <div class="carousel-item">
                            <img src="~/images/LaptopCategory.jpg" class="d-block w-100" style="filter:blur(4px) brightness(75%)" alt="...">
                            <div class="carousel-caption d-md-block">
                                <h3 class="text-white">Laptops</h3>
                                <h5 class="text-white-50">Handred Of Laptops Of Couarse, You Will Find What You Like </h5>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="~/images/CarCategory.png" class="d-block w-100" style="filter:blur(2px) brightness(75%)" alt="...">
                            <div class="carousel-caption d-md-block">
                                <h3 class="text-white" >Cars</h3>
                                <h5 class="text-white-50">Handred Of Cars Of Couarse, You Will Find What You Like </h5>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="~/images/PhoneCategory.png" class="d-block w-100 " style="filter:blur(4px) brightness(75%)" alt="...">
                            <div class="carousel-caption d-md-block">
                                <h3 class="text-white" >Phones</h3>
                                <h5 class="text-white-50">Handred Of Phones Of Couarse, You Will Find What You Like </h5>
                            </div>
                        </div>
                    </div>

                    <!-- Controls -->
                    <button class="carousel-control-prev d-flex align-items-center justify-content-center" type="button"
                            data-bs-target="#productsCarousel" data-bs-slide="prev"
                            style="width:45px; height:45px; top:50%;  transform:translateY(-50%); background:rgba(0,0,0,0.5); border-radius:50%;">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>

                    <button class="carousel-control-next d-flex align-items-center justify-content-center" type="button"
                            data-bs-target="#productsCarousel" data-bs-slide="next"
                            style="width:45px; height:45px; top:50%;  transform:translateY(-50%); background:rgba(0,0,0,0.5); border-radius:50%;">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>