LazmekUI/Areas/Admin/Controllers/CategoryController.cs
using DataAccess.Repository;
using DataAccess.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyProject.Models;
using Utility;




namespace MyProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitofwork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Category> list = _unitofwork.Category.GetAll().ToList();
            return View(list);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category obj)
        {

            if (ModelState.IsValid)
            {
                _unitofwork.Category.Add(obj);
                _unitofwork.Save();
                TempData["success"] = "Done Created !";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var Categoryfromdb = _unitofwork.Category.Get(x => x.Id == id);
            if (Categoryfromdb == null)
            {
                return NotFound();
            }
            return View(Categoryfromdb);
        }
        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitofwork.Category.Update(obj);
                _unitofwork.Save();
                TempData["success"] = "Done Updated !";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var Categoryfromdb = _unitofwork.Category.Get(x => x.Id == id);
            if (Categoryfromdb == null)
            {
                return NotFound();
            }
            return View(Categoryfromdb);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            var exist = _unitofwork.Category.Get(x => x.Id == id);
            if (exist == null)
            {
                return NotFound(id);
            }

            _unitofwork.Category.Remove(exist);
            _unitofwork.Save();
            TempData["delete"] = "Done Deleted !";
            return RedirectToAction("Index");
        }

    }//end controller
}

LazmekUI/Areas/Admin/Views/Category/Create.cshtml
@model Category
<div class="card mt-4 border-0 shadow bg-dark-mode text-white-50">
    <div class="card-header bg-gradient  py-3 ms-0" style="background-color:goldenrod">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class=" text-white py-2">Create Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3">
                <div class=" form-floating py-3 col-12">
                    <label asp-for="Name" class="ms-0"></label>
                    <input asp-for="Name" class="form-control border-0 shadow bg-dark-mode text-light " />
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>                
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <input type="submit" value="Create" class="btn btn-warning form-control " />
                    </div>
                    <div class="col-6 col-md-3">
                        <a class="btn btn-outline-light form-control" asp-controller="Category" asp-action="Index">Back to home</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

LazmekUI/Areas/Admin/Views/Category/Delete.cshtml
@model Category

<div class="card mt-4 border-0 shadow bg-dark-mode text-white-50">
    <div class="card-header bg-gradient py-3 ms-0" style="background-color:goldenrod">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class=" text-white py-2"> Delete Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border border-dark p-3">
                <div class=" form-floating py-3 col-12 ">
                    <label asp-for="Name" class="ms-0 "></label>
                    <input asp-for="Name" disabled class="form-control border-0 shadow bg-dark-mode text-opacity-75 text-light " />
                </div>                
                <div class="row mt-2">
                    <div class="col-6 col-md-3">
                        <input type="submit" value="Delete" class="btn btn-danger form-control " />
                    </div>
                    <div class="col-6 col-md-3">
                        <a class="btn btn-outline-light form-control" asp-controller="Category" asp-action="Index">Back to home</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

LazmekUI/Areas/Admin/Views/Category/Edit.cshtml
@model Category

<div class="card mt-4 border-0 shadow bg-dark-mode text-white-50">
    <div class="card-header bg-gradient  py-3 ms-0" style="background-color:goldenrod">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class=" text-white py-2">Edit Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border border-dark p-3">
                <div class=" form-floating py-3 col-12">
                    <label asp-for="Name" class="ms-0"></label>
                    <input asp-for="Name" class="form-control border-0 shadow text-light bg-dark-mode " />
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>                
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <input type="submit" value="Save Changes" class="btn btn-warning form-control" />
                    </div>
                    <div class="col-6 col-md-3">
                        <a class="btn btn-outline-light form-control" asp-controller="Category" asp-action="Index">Back to home</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

LazmekUI/Areas/Admin/Views/Category/Index.cshtml
@model List<Category>
<div class="card mt-4 border-0 shadow bg-dark-mode text-light">
    <div class="card-header bg-gradient py-3 ms-0" style="background-color:goldenrod">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class=" text-white py-2"> Category List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row py-3">
            <div class="col-12 text-end">
                <a class="btn btn-primary" asp-controller="Category" asp-action="Create"> <i class="bi bi-plus-circle"></i> Add New Category </a>
            </div>
        </div>
        <table class=" table table-bordered table-striped table-dark">
            <thead>
                <tr>
                    <th>Name</th>                    
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var Category in Model)
                {
                    <tr>
                        <td>@Category.Name</td>                        
                        <td>
                            <div class="w-75 btn-group ">
                                <a class="btn btn-danger" asp-controller="Category" asp-action="Delete" asp-route-id="@Category.Id"><i class="bi bi-trash"></i></a>
                                <a class="btn btn-primary" asp-controller="Category" asp-action="Edit" asp-route-id="@Category.Id"><i class="bi bi-pencil-square"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>