LazmekUI/Areas/Admin/Controllers/OrderController.cs
using DataAccess.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models;
using Models.ViewModels;
using Stripe;
using Stripe.Checkout;
using System.Security.Claims;
using Utility;

namespace MyProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =$"{SD.Role_Admin},{SD.Role_Employee}")]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        [BindProperty]
        private OrderVM orderVM {  get; set; }
        public OrderController(IUnitOfWork unitOfWork)
        {
           _unitofwork = unitOfWork;
           
        }
        public IActionResult Index()
        {
            
            return View();
        } 
        public IActionResult Details(int orderId)
        {
            orderVM = new OrderVM
            {
                orderHeader = _unitofwork.OrderHeader.Get(x=>x.Id==orderId, includeProperties: "user"),
                orderDetail = _unitofwork.OrderDetail.GetAll(x => x.OrderHeaderId == orderId, includeProperties:"product" ).ToList()
            };            
            return View(orderVM);
        }
        [HttpPost(nameof(Details))]
        public IActionResult UpdateOrderDetail()
        {
            var orderHeaderFromDb = _unitofwork.OrderHeader.Get(x=>x.Id==orderVM.orderHeader.Id);

            orderHeaderFromDb.Name= orderVM.orderHeader.Name;
            orderHeaderFromDb.PhoneNumber= orderVM.orderHeader.PhoneNumber;
            orderHeaderFromDb.StreetAddress= orderVM.orderHeader.StreetAddress;
            orderHeaderFromDb.Country= orderVM.orderHeader.Country;
            orderHeaderFromDb.City= orderVM.orderHeader.City;
            orderHeaderFromDb.PostalCode= orderVM.orderHeader.PostalCode;
            if (!string.IsNullOrEmpty(orderHeaderFromDb.Carrier))
            {
                orderHeaderFromDb.Carrier = orderHeaderFromDb.Carrier;
            }
            if (!string.IsNullOrEmpty(orderHeaderFromDb.TrackingNumber))
            {
                orderHeaderFromDb.TrackingNumber = orderHeaderFromDb.TrackingNumber;
            }
            _unitofwork.OrderHeader.Update(orderHeaderFromDb);
            _unitofwork.Save();
            TempData["success"] = "Order details Updated successfuly!";

            return RedirectToAction(nameof(Details), new { orderHeaderId = orderVM.orderHeader.Id});
        }
        [HttpPost]        
        public IActionResult StartProccing()
        {            
            _unitofwork.OrderHeader.UpdateStatus(orderVM.orderHeader.Id, SD.StatusInProcess);
            _unitofwork.Save();
            TempData["success"] = "Order details Updated successfuly!";
            return RedirectToAction(nameof(Details), new { orderHeaderId = orderVM.orderHeader.Id});
        }
        [HttpPost]        
        public IActionResult ShipOrder()
        {
            var orderHeaderFromDb = _unitofwork.OrderHeader.Get(o=>o.Id==orderVM.orderHeader.Id);
            orderHeaderFromDb.Carrier = orderVM.orderHeader.Carrier;
            orderHeaderFromDb.TrackingNumber = orderVM.orderHeader.TrackingNumber;
            orderHeaderFromDb.OrderStatus = SD.StatusShipped;
            orderHeaderFromDb.ShippingDate= DateTime.Now;
            
            _unitofwork.OrderHeader.Update(orderVM.orderHeader);
            _unitofwork.Save();
            TempData["success"] = "Order details Updated successfuly!";
            return RedirectToAction(nameof(Details), new { orderHeaderId = orderVM.orderHeader.Id});
        }
        [HttpPost]        
        public IActionResult CancelOrder()
        {
            var orderHeaderFromDb = _unitofwork.OrderHeader.Get(u=>u.Id==orderVM.orderHeader.Id);
            if (orderHeaderFromDb.OrderStatus == SD.StatusApproved)
            {
                var options = new RefundCreateOptions()
                {
                    Reason=RefundReasons.RequestedByCustomer,
                    PaymentIntent=orderHeaderFromDb.PaymentIntentId
                };
                var service = new RefundService();
                Refund refund=service.Create(options);
                _unitofwork.OrderHeader.UpdateStatus(orderHeaderFromDb.Id,SD.StatusCancelled,SD.StatusRefunded);
            }
            else
            {
                _unitofwork.OrderHeader.UpdateStatus(orderHeaderFromDb.Id, SD.StatusCancelled, SD.StatusCancelled);
            }
            _unitofwork.Save();

            TempData["delete"] = "Order Canceled successfuly!";
            return RedirectToAction(nameof(Details), new { orderHeaderId = orderVM.orderHeader.Id });
        }
        [HttpPost(nameof(Details))]        
        public IActionResult Details_PAY_NOW()
        {
            orderVM.orderHeader= _unitofwork.OrderHeader.Get(x => x.Id == orderVM.orderHeader.Id, includeProperties: "user");
            orderVM.orderDetail= _unitofwork.OrderDetail.GetAll(x => x.OrderHeaderId == orderVM.orderHeader.Id, includeProperties: "product");

            //payment Logic
            var Domin = "https://localhost:7224";
            var options = new Stripe.Checkout.SessionCreateOptions
            {
                SuccessUrl = Domin + $"/Admin/order/PaymentConfirmation?orderHeaderId={orderVM.orderHeader.Id}",
                CancelUrl = Domin + $"/Admin/order/Details?orderHeaderId={orderVM.orderHeader.Id}",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
            };
            foreach (var cart in  orderVM.orderDetail)
            {
                var sessionLineItem = new SessionLineItemOptions()
                {
                    PriceData = new SessionLineItemPriceDataOptions()
                    {
                        UnitAmount = (long)cart.Price * 100,    // convert 20.75$ => 2075
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions()
                        {
                            Name = cart.product.Title
                        }
                    },
                    Quantity = cart.Count
                };
                options.LineItems.Add(sessionLineItem);
            }
            var service = new SessionService();
            Session session = service.Create(options);
            _unitofwork.OrderHeader.UpdateStripePaymentId(orderVM.orderHeader.Id, session.Id, session.PaymentIntentId);
            _unitofwork.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }
        
        public IActionResult PaymentConfirmation(int orderHeaderId)
        {
            orderVM.orderHeader = _unitofwork.OrderHeader.Get(x => x.Id == orderHeaderId);
            if (orderVM.orderHeader!=null)
            {
                var service = new SessionService();
                Session session = service.Get(orderVM.orderHeader.SessionId);
                if (session.PaymentStatus.ToLower() == "paid")
                {

                    _unitofwork.OrderHeader.UpdateStripePaymentId(orderVM.orderHeader.Id, session.Id, session.PaymentIntentId);
                    _unitofwork.OrderHeader.UpdateStatus(orderVM.orderHeader.Id, orderVM.orderHeader.OrderStatus, SD.PaymentStatusApproved);
                    _unitofwork.Save();
                }                               
            }
            return View(orderHeaderId);
        }
        #region Api Call 
        [HttpGet]
        public IActionResult GetAll(string status)
        {
            IEnumerable<OrderHeader> orderHeadersList;
            if (User.IsInRole(SD.Role_Employee)|| User.IsInRole(SD.Role_Admin))
            {
                orderHeadersList = _unitofwork.OrderHeader.GetAll(includeProperties: "user").ToList();
                switch (status)
                {
                    case "inprocess": orderHeadersList = orderHeadersList.Where(x => x.OrderStatus == SD.StatusInProcess); break;
                    case "completed": orderHeadersList = orderHeadersList.Where(x => x.OrderStatus == SD.StatusShipped); break;
                    case "approved": orderHeadersList = orderHeadersList.Where(x => x.OrderStatus == SD.StatusApproved); break;
                }
            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                orderHeadersList = _unitofwork.OrderHeader.GetAll(u => u.UserID == userId, includeProperties: "user");
            }
            
            return Json(new { data = orderHeadersList});
        }
        #endregion
    }//end controller
}

LazmekUI/Areas/Admin/Views/Order/Index.cshtml
@{
    var status = Context.Request.Query["status"];
    var InProcess = "text-white bg-dark";
    var Pending = "text-white bg-dark";
    var Completed = "text-white bg-dark";
    var Approved = "text-white bg-dark";
    var All = "text-white bg-dark";

    switch (status)
    {
        case "pending": Pending = "active text-white bg-warning"; break;
        case "inprocess": InProcess = "active text-white bg-warning"; break;
        case "completed": Completed = "active text-white bg-warning"; break;
        case "approved": Approved = "active text-white bg-warning"; break;
        default: All = "active text-white bg-warning"; break;
    }
}
<div class="card  border-0 shadow my-5 bg-dark-mode text-white">
    <div class="card-header bg-gradient   py-3 ms-0">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class=" text-white py-2"> Order List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="d-flex justify-content-between pb-5 pt-2">
            <span></span>
            <ul class="list-group list-group-horizontal-sm">
                <a class="text-decoration-none" asp-controller="Order" asp-action="Index" asp-route-status="inprocess">
                <li class="list-group-item @InProcess">In Process</li>
                </a>
                <a class="text-decoration-none" asp-controller="Order" asp-action="Index" asp-route-status="pending">
                <li class="list-group-item @Pending">Payment Pending</li>
                </a>
                <a class="text-decoration-none" asp-controller="Order" asp-action="Index" asp-route-status="completed">
                <li class="list-group-item @Completed">Completed</li>
                </a>
                <a class="text-decoration-none" asp-controller="Order" asp-action="Index" asp-route-status="approved">
                <li class="list-group-item @Approved">Approved</li>
                </a>
                <a class="text-decoration-none" asp-controller="Order" asp-action="Index" asp-route-status="all">
                <li class="list-group-item @All">All</li>
                </a>
            </ul>
        </div>
        <table id="tabledata" class=" table table-bordered table-dark table-striped">
            <thead>
                <tr>

                    <th>ID</th>
                    <th>Name</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                    <th>status</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts {
    <script src="~/js/Order.js"></script>
}

LazmekUI/Areas/Admin/Views/Order/PaymentConfirmation.cshtml
@model int 
<div class="container row pt-4 bg-dark-mode text-white">
    <div class="col-12 text-center">
        <h1 class="text-white text-center">payment successful!</h1>
        Your Order Numper IS : @Model
        <br/>
        <br/>
        <img src="~/images/lawn_leaf.jpg" width="65%" />
    </div>
    <div class=" col-12 text-center text-bg-warning">
        Your Payment has been placed Successfully!
        <a asp-action="Details" asp-route-orderHeaderId="@Model" class="btn btn-primary">Back to Order Details</a>
    </div>
</div>